name: assembly
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.4
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.1
  - azure-identity-cpp=1.13.2
  - azure-storage-blobs-cpp=12.16.0
  - azure-storage-common-cpp=12.12.0
  - azure-storage-files-datalake-cpp=12.14.0
  - bcftools=1.23
  - biopython=1.86
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - choreographer=1.2.1
  - colorama=0.4.6
  - exceptiongroup=1.3.1
  - filtlong=0.3.1
  - flye=2.9.6
  - gflags=2.2.2
  - glog=0.7.1
  - gsl=2.7
  - htslib=1.23
  - icu=78.2
  - iniconfig=2.3.0
  - k8=1.2
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-aarch64=2.45.1
  - libabseil=20250512.1
  - libarrow=23.0.0
  - libarrow-acero=23.0.0
  - libarrow-compute=23.0.0
  - libarrow-dataset=23.0.0
  - libarrow-substrait=23.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcurl=8.18.0
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libiconv=1.18
  - liblapack=3.11.0
  - liblzma=5.8.2
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=23.0.0
  - libpng=1.6.54
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libthrift=0.22.0
  - libutf8proc=2.11.3
  - libuuid=2.41.3
  - libxcrypt=4.4.36
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - logistro=2.0.1
  - lz4-c=1.10.0
  - minimap2=2.30
  - nanoget=1.19.4
  - nanoplot=1.46.2
  - narwhals=2.16.0
  - ncurses=6.5
  - nlohmann_json=3.12.0
  - numpy=2.4.2
  - openssl=3.6.1
  - orc=2.2.2
  - orjson=3.11.5
  - packaging=26.0
  - pandas=3.0.0
  - perl=5.32.1
  - pip=26.0.1
  - plotly=6.5.2
  - pluggy=1.6.0
  - prometheus-cpp=1.3.0
  - pyarrow=23.0.0
  - pyarrow-core=23.0.0
  - pygments=2.19.2
  - pysam=0.23.3
  - pytest=9.0.2
  - pytest-timeout=2.4.0
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-kaleido=1.2.0
  - python_abi=3.12
  - re2=2025.11.05
  - readline=8.3
  - s2n=1.6.2
  - samtools=1.23
  - scipy=1.17.0
  - setuptools=80.10.2
  - simplejson=3.20.2
  - six=1.17.0
  - snappy=1.2.2
  - tk=8.6.13
  - tomli=2.4.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - wheel=0.46.3
  - zlib=1.3.1
  - zstd=1.5.7
prefix: /home/rebekah-hest/miniconda3/envs/assembly
